---
priority: 20
privileged: false
inline: |
  [[ $(which docker >/dev/null 2>&1; echo $?) -ne 0 ]] && wget -qO- https://get.docker.com/ | sudo sh
  [[ $(egrep -q "^docker:.+\b${SUDO_USER}\b" /etc/group; echo $?) -ne 0 ]] && sudo usermod -aG docker $SUDO_USER

  docker --version | head -n1 | awk '{ print "Docker version: "$3 }'
